### ISSUE TITLE
'BaseParser' is not defined in parse_photos.py

### ISSUE THREAD

**Issue by aebrookes** [symroe/CouncillorData#1]
I've been having a bit of play with this and I've not been able to identify what must be a dependency I am missing. When I run parse_photos.py I receive the following error: 

> Traceback (most recent call last):
>   File "parse_photos.py", line 3, in <module>
>     class CouncillorPhotoParser(BaseParser):
> NameError: name 'BaseParser' is not defined

My initial assumption is that I'm missing a dependency but I note that the import of base_parser doesn't seem to be generating an error and I can import BeautifulSoup without a problem.

**Comment by aebrookes** [comment]
Simply changing how the base_parser module was being imported (see 3e10f7c) fixed this issue for me.

**Comment by symroe** [comment]
I think this might be a python version issue – I'm on 3.4 where the way imports work was changed.  

I suspect using python 3.4 or adding `from __future__ import absolute_import` before that line might fix it too.

**Comment by symroe** [comment]
Oh no, I'm wrong – this was just a typo on my part!  I'll import your commit :)  Thanks!

**Comment by symroe** [comment]
I've cherry-picked out a few of your commits and shoved them on master here.  I'm happy to do this in future for other commits too – if possible can you keep more generic commits apart from your specific ones?  No worries if not - I'm happy that you're working on it! :)

**Comment by aebrookes** [comment]
Thanks for the update. I was trying to have a separate branch for my SKDC specific work. This is my first time on GitHub so I'm still learning the best way to structure projects.
